### ISSUE TITLE
App crashes when GoogleMapsNavigationView is initiated after a hot-restart (iOS only)

### ISSUE THREAD

**Issue by rui-reazon99** [googlemaps/flutter-navigation-sdk#117]
#### Environment details

1. flutter-navigation-sdk: 0.3.0
2. MacOS 14.5（23F79）
3. Flutter SDK: 3.22.1

#### Steps to reproduce

The following procedure was carried out inside the example directory using the iOS emulator:

1. Open the Map page within the example app.
2. Use the hot-restart function to restart the app.
3. After the hot-restart, upon re-entering the map page, the app crashes immediately when the GoogleMapsNavigationView instance is initiated.

https://github.com/googlemaps/flutter-navigation-sdk/assets/130721404/af028b7f-33d8-4cd9-b45f-c0406b99a7a0

**Comment by illuminati1911** [comment]
@rui-reazon99 Thank you for reporting the issue.

**Comment by mosesgameli** [comment]
@illuminati1911 any update on this

**Comment by illuminati1911** [comment]
@mosesgameli @rui-reazon99 Just made a fix candidate for it. Sorry for the delay.
I'll let you know when it's available in the release.
