### ISSUE TITLE
The map does not show up when start the example app(Both Android and iOS)

### ISSUE THREAD

**Issue by egami-takichi** [googlemaps/flutter-navigation-sdk#128]
I would like to incorporate flutter-navigation-sdk into an application I am developing, so I am trying to check its operation with an example first.

#### Environment details

1.flutter-navigation-sdk: 0.3.0
2.MacOS 14.0
3.Flutter SDK: 3.22.1

#### flutter doctor
```
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.87.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

#### Verification device
1.AQUOS sense4 (Android10)
2.iPhoneSE 2nd generation (iOS15.1)

#### Steps to reproduce
The following occurs when the sample application in the example directory is started.

##### iOS
When opening the Navigation and Map screens, the following error message is displayed and GoogleMap is not displayed, resulting in a blank screen.
```
This application has been blocked by the Google Navigation SDK. This might be because of an incorrectly registered key.
```

<img src="https://github.com/user-attachments/assets/d74d463d-e10a-4e28-8f27-63852fb6de7c" width="250">

We have confirmed that the API_KEY specified in "dart-define" is the same as the one defined in Google Cloud.

##### Android
I tried to start the example app according to the installation procedure, but an error about glide_module occurred in my environment and the map was not displayed, so I created a class referring to [here](https://github.com/bumptech/glide/issues/4823) to solve the problem.
However, even after solving the glide_module error, I still get a blank screen, just like on iOS.

<img src="https://github.com/user-attachments/assets/e465a568-cf97-4b4d-b4c4-c2b94fe13fe4" width="250">

#### Android execution result log
```
/flutter (29135): Navigator has been initialized: true
D/TrafficStats(29135): tagSocket(153) with statsTag=0x99e6744e, statsUid=-1
E/FrameEvents(29135): updateAcquireFence: Did not find frame.
W/Parcel  (29135): Expecting binder but got null!
E/ThemeUtils(29135): View class com.google.android.apps.gmm.base.views.squeezedlabel.SqueezedLabelView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
W/igation_example(29135): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
E/ThemeUtils(29135): View class com.google.android.apps.gmm.base.views.squeezedlabel.SqueezedLabelView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
E/ThemeUtils(29135): View class com.google.android.apps.gmm.base.views.squeezedlabel.SqueezedLabelView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
W/Resources(29135): Drawable com.google.maps.flutter.navigation_example:drawable/generic_above_shadow has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
W/Resources(29135): java.lang.RuntimeException
W/Resources(29135):     at android.content.res.Resources.getDrawable(Resources.java:908)
W/Resources(29135):     at com.google.android.libraries.navigation.internal.oo.a.a(PG:25)
...
W/Resources(29135):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/Resources(29135):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/FrameEvents(29135): updateAcquireFence: Did not find frame.
E/FrameEvents(29135): updateAcquireFence: Did not find frame.
```

**Comment by caio1985** [comment]
A few things to try:

- Can you try to use an API key without restrictions to see if that works and then restrict it to see what might be the problem?
- Have you enabled Maps SDK for Android and iOS and Navigation SDK in your project console which the API key you are using belongs to?

@jokerttu can you check if using [this](https://github.com/bumptech/glide/issues/4823) approach could be causing this issue? Thanks!

**Comment by egami-takichi** [comment]
Thank you for your response,

> Can you try to use an API key without restrictions to see if that works and then restrict it to see what might be the problem?

I created a key with no application and API restrictions, but the result was the same.

> Have you enabled Maps SDK for Android and iOS and Navigation SDK in your project console which the API key you are using belongs to?

I confirmed that both of these are enabled.

**Comment by jokerttu** [comment]
@egami-takichi 
Please follow the instructions how to use the API_KEY in the [README.md file](https://github.com/googlemaps/flutter-navigation-sdk?tab=readme-ov-file#installation).
If you want to use the the dart-define like in examples, please read the api key from dart defines like in [example code](https://github.com/googlemaps/flutter-navigation-sdk/blob/main/example/ios/Runner/AppDelegate.swift#L40).

**Comment by egami-takichi** [comment]
@jokerttu 

```
flutter run --dart-define MAPS_API_KEY=my_api_key
```
I have run the app as described above, but I get the same error.
In debug mode, the variable "mapsApiKey" in `AppDelegate.swift` was assigned the API key set by dart-define.

Is this the correct procedure?

**Comment by jokerttu** [comment]
@egami-takichi

I confirmed that the example app works correctly (on iOS and Android) with a clean cloned repository when providing the API key using dart-define.

The issue you're experiencing is most likely due to incorrect permissions for the API key or certain services not being enabled. Please ensure that the following APIs are enabled in your Google Cloud Console: Navigation API, Maps SDK for iOS, and Maps SDK for Android.

**Comment by iwata-yasuaki** [comment]
@jokerttu 

Thank you for your confirmation, I will response on behalf of @egami-takichi . We are on the same team.

I have checked the API activation and API Key settings. The screenshot is pasted below. I don't see any problem, but is there anything inappropriate from your point of view?


Navigation SDK
<img width="1235" alt="image" src="https://github.com/user-attachments/assets/eea7ace8-2ad7-4c49-a068-fac41ee233b5">

Maps SDK for iOS/Android
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/b6406c4f-f174-4bf3-859b-40692e07787f">

API Key for iOS
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/75e80570-2f86-4c48-9107-57ba3a14cb89">

API Key for Android
<img width="1221" alt="image" src="https://github.com/user-attachments/assets/92d85889-cedf-46a3-afd0-98192ad72a47">

**Comment by ArturoSalazarB16** [comment]
Hey there! @iwata-yasuaki 

To confirm whether this is an issue with the Flutter library versus a configuration problem, can you please check if the same API key works well with the native sample app? https://github.com/googlemaps-samples/android-navigation-samples

**Comment by iwata-yasuaki** [comment]
@ArturoSalazarB16 @jokerttu @caio1985 

Thank you for your support. The problem has been resolved. The cause was due to improper GCP project used and internal network limitations. By using the proper GCP project and correcting the internal network restrictions, we were able to display the map. Sorry, there was nothing wrong with this SDK itself. Thank you.

**Comment by WaseekSenju** [comment]
@egami-takichi, Sorry to ping you. But can you share some information how the issue was solved for you? I am using the example repo and getting the same issue for both iOS and android. I can confirm that my tokens are permissions are valid and I can see the stats being displayed on the GCP. 

![Image](https://github.com/user-attachments/assets/9e64e574-e21b-4b99-af7e-5faa30eef67a)

![Image](https://github.com/user-attachments/assets/7076ff53-a6f6-4e26-bfb9-169d0839727a)

**Comment by caio1985** [comment]
@WaseekSenju have you enabled the API on your GCP project after following the README file instructions? Ensure you also have an API key that is not restricted to Maps and Navigation SDK APIs.

**Comment by zaynekomichi** [comment]
@WaseekSenju did you manage to solve this

**Comment by WaseekSenju** [comment]
@zaynekomichi I don't remember exactly but it was either 2 things:
1- there was official bug on iOS 18.3 that caused this issue on simulator
2- I had not enabled the API services from GCP (this was more like it)

**Comment by zaynekomichi** [comment]
@WaseekSenju I hadn't enabled the API service. Thanks!!
