### ISSUE TITLE
Duplicate Class Error Found in Android and Google

### ISSUE THREAD

**Issue by lavkushry1** [googlemaps/flutter-navigation-sdk#129]
I have these many Dependencies 
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.0
  google_navigation_flutter: ^0.3.0
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  dio: ^5.5.0+1
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  audioplayers: ^6.0.0
  carousel_slider: ^4.2.1
  flutter_sound: ^9.9.5
  image_picker: ^1.1.2
  flutter_polyline_points: ^2.1.0
  intl: ^0.19.0
  http: ^1.2.2
  uuid: ^4.4.2
  device_info_plus: ^9.1.0
  cupertino_icons: ^1.0.6

When I run my Project in Android Emulator then I got error like

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.gms.maps.CameraUpdate found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.CameraUpdateFactory found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$CancelableCallback found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$InfoWindowAdapter found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnCameraChangeListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnCameraIdleListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnCameraMoveCanceledListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnCameraMoveListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnCameraMoveStartedListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnCircleClickListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnGroundOverlayClickListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnIndoorStateChangeListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnInfoWindowClickListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnInfoWindowCloseListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnInfoWindowLongClickListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnMapCapabilitiesChangedListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnMapClickListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnMapLoadedCallback found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnMapLongClickListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnMarkerClickListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnMarkerDragListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnMyLocationButtonClickListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnMyLocationChangeListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnMyLocationClickListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnPoiClickListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnPolygonClickListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$OnPolylineClickListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMap$SnapshotReadyCallback found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.GoogleMapOptions found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.LocationSource found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.LocationSource$OnLocationChangedListener found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.MapFragment found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.MapView found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.MapsInitializer found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.MapsInitializer$Renderer found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.OnMapReadyCallback found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
     Duplicate class com.google.android.gms.maps.OnMapsSdkInitializedCallback found in modules jetified-navigation-5.1.1-runtime (com.google.android.libraries.navigation:navigation:5.1.1) and jetified-play-services-maps-18.2.0-runtime (com.google.android.gms:play-services-maps:18.2.0)
 

and When I Run this app in iOS Simulator then

   [!] CocoaPods could not find compatible versions for pod "GoogleMaps":
      In Podfile:
        GoogleMaps (= 8.4.0)

        google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`) was resolved to 0.0.1, which depends on
          GoogleMaps (< 10.0, >= 8.4)

        google_navigation_flutter (from `.symlinks/plugins/google_navigation_flutter/ios`) was resolved to 0.0.1, which depends on
          GoogleNavigation (= 5.3.1) was resolved to 5.3.1, which depends on
            GoogleMaps (= 8.3.1)

" 
How to Fix these Error

**Comment by jokerttu** [comment]
Hi @lavkushry1 
The `google_maps_flutter` package is not compatible with the `google_navigation_flutter` package because both have their `GoogleNavigation` pod dependencies. For this reason, the `google_navigation_flutter` package includes implementations for most of the Google Maps features.

Are there any specific features from the google_maps_flutter package that you need and are missing in the google_navigation_flutter package?

**Comment by aabid-implies** [comment]
@jokerttu can we use our custom svg marker in google_navigation_flutter's GoogleMapsMapView?

**Comment by jokerttu** [comment]
@aabid-implies 
not directly, but you can render the svg as a PNG image and use that as a custom marker.

If you use `flutter_svg` you can follow this process:
1. Get the picture from PictureInfo with picture getter: https://pub.dev/documentation/flutter_svg/latest/flutter_svg/PictureInfo/picture.html
2. Render it as an image with https://api.flutter.dev/flutter/dart-ui/Picture/toImage.html
3. Get bytedata: `final ByteData? bytes = await image.toByteData(format: ui.ImageByteFormat.png,);`
4. Call registerBitmapImage with ByteData: `final ImageDescriptor icon = registerBitmapImage(bitmap: bytes!, imagePixelRatio: imagePixelRatio);`

See how custom images are used in example app at https://github.com/googlemaps/flutter-navigation-sdk/blob/main/example/lib/utils/waypoint_marker.dart#L41-L46
