### ISSUE TITLE
Current self location not updating in turn by turn navigation. 

### ISSUE THREAD

**Issue by DhirajMakane** [googlemaps/flutter-navigation-sdk#143]
Hi, 
The current user location is not updating in turn-by-turn navigation. 

Environment details

1. google_navigation_flutter: ^0.3.0
2. Observed for both android and ios Device
3. Flutter - 3.22.3
4. Location Permissions are enabled

Permissions added 
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

Steps to reproduce

  1. Set destination and origin. 
  2. Open Google Maps for turn-by-turn navigation
  3. Initial self-location and the route are displayed on the map
  6. Now Walk/drive and check for the current self-location in the map
  7. Current self-location is not updated. 
  8. After taking turns also self-location is not updated.
  9. After clicking on recenter also self-location is not updated.

Code Snippet
Future<void> _startNavigation() async {
    // popup for the terms and condition
    if (!await GoogleMapsNavigator.areTermsAccepted()) {
      await GoogleMapsNavigator.showTermsAndConditionsDialog(
        'Sample App',
        'Sample App',
      );
    }

    await GoogleMapsNavigator.initializeNavigationSession();
    await _setupListeners();

    /// Simulate location.
    await GoogleMapsNavigator.simulator.setUserLocation(current location);

    // add way points
    var wayPoints = <NavigationWaypoint>[
      NavigationWaypoint.withLatLngTarget(
        title: widget.destinationTitle,
        target: widget.destinationLocation,
      ),
    ];
    final Destinations msg = Destinations(
        waypoints: wayPoints,
        displayOptions: NavigationDisplayOptions(showDestinationMarkers: true),
        routingOptions:
            RoutingOptions(travelMode: NavigationTravelMode.twoWheeler));

    final NavigationRouteStatus status =
        await GoogleMapsNavigator.setDestinations(msg);

    if (status == NavigationRouteStatus.statusOk) {
      await GoogleMapsNavigator.startGuidance();

      await _navigationViewController
          .followMyLocation(CameraPerspective.tilted);

    }
  }

Thanks!

**Comment by jokerttu** [comment]
Hi @DhirajMakane 

If I understand correctly, you want to use the real device location. In that case, you should not simulate the location. Removing the following line should help:
`/// Simulate location.
await GoogleMapsNavigator.simulator.setUserLocation(current location);`

If you want to simulate the routepath, start simulation with:
`await GoogleMapsNavigator.simulator.simulateLocationsAlongExistingRouteWithOptions(SimulationOptions(speedMultiplier: 1),);`

**Comment by DhirajMakane** [comment]
Thanks @jokerttu. It's working as expected. Closing this issue
