### ISSUE TITLE
Compatibility Issue: Unable to Run google_maps_navigation with google_maps_flutter

### ISSUE THREAD

**Issue by OrKahilaPumba** [googlemaps/flutter-navigation-sdk#148]
#### Environment details

2. OS type and version - IOS

#### Steps to reproduce

1. Add both google_maps_flutter and google_maps_navigation to pubspec.yaml.
2. Run flutter pub get to install dependencies.
3. Navigate to the ios folder and run pod install.
4. Observe the error regarding incompatible GoogleMaps versions.

# example
CocoaPods could not find compatible versions for pod "GoogleMaps":
  In Podfile:
    google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`) was resolved to 0.0.1, which depends on
      GoogleMaps (< 10.0, >= 8.4)

    google_maps_navigation (from `.symlinks/plugins/google_maps_navigation/ios`) was resolved to 0.0.1, which depends on
      GoogleNavigation (= 5.3.1) was resolved to 5.3.1, which depends on
        GoogleMaps (= 8.3.1)

Expected Behavior: I should be able to use both google_maps_navigation and google_maps_flutter together in the same Flutter project without any dependency conflicts.

Proposed Solutions:

1. Update the google_maps_navigation package to support newer versions of the GoogleMaps pod.
2. Provide a workaround to allow both packages to coexist in the same project.

Thanks!

**Comment by OrKahilaPumba** [comment]
Hello Joonas, thanks for looking into this

Our app helps users to find parking on the street, and we use google maps
on our main screen. The user has a button to start search for parkings,
when he does, it displays on the map all available parking spots around his
destination. The user can choose to navigate to a certain parking spot, and
thats where we want to use the navigation sdk. I'm also attaching some
screenshots to help you understand our use.

Thanks for your help!

**Comment by hkm5558** [comment]
> Hi @OrKahilaPumba,
> 
> The conflict arises because both `google_maps_flutter` and `flutter_navigation_sdk` depend on the GoogleMaps SDK. Since the Navigation SDKs for Android and iOS have their own GoogleMaps SDK dependencies, this leads to the incompatibility you're encountering.
> 
> Note that the `flutter_navigation_sdk` includes ways to control the map itself, similar to what `google_maps_flutter` offers.
> 
> Could you let us know which specific features of `google_maps_flutter` you're looking to use that are missing from the `flutter_navigation_sdk`? This will help us better support your use case. If there are essential features you're missing, we can consider adding them to the `flutter_navigation_sdk`.
> 
> We're also planning to document this incompatibility in the README to help prevent confusion for other users.
> 
> Thanks for your feedback!

There is no takeSnapshot method，How should I get screenshots from the Map sdk in the current sdk?

**Comment by reubendeekay** [comment]
This issue has not been fixed. I cannot be able to use this package with the default google_map_flutter package

**Comment by jokerttu** [comment]
Hi @reubendeekay ,

> The conflict arises because both `google_maps_flutter` and `flutter_navigation_sdk` depend on the GoogleMaps SDK. Since the Navigation SDKs for Android and iOS have their own GoogleMaps SDK dependencies, this leads to the incompatibility you're encountering.

As this package is a wrapper for the native Navigation SDKs, it cannot resolve this issue directly. You have a couple of options:

1. Use only the navigation package, which also supports the classic map view.
2. Force dependency resolution in your Gradle code and iOS implementation. However, this approach will only work if you use package versions of `google_maps_flutter` and `flutter_navigation_sdk` that depend on the same version of the underlying GoogleMaps SDK.

**Comment by v62win** [comment]
@OrKahilaPumba how did u fix this issue can u help me

**Comment by OrKahilaPumba** [comment]
> @OrKahilaPumba how did u fix this issue can u help me

Sorry man, we didn't find a solution for the problem, we just stopped using google_maps_flutter

**Comment by jokerttu** [comment]
@v62win The issue is explained here:
https://github.com/googlemaps/flutter-navigation-sdk?tab=readme-ov-file#compatibility-with-other-libraries
