### ISSUE TITLE
[docs] Delete doc/ folder?

### ISSUE THREAD

**Issue by bamnet** [googlemaps/flutter-navigation-sdk#155]
Currently the [/doc folder](https://github.com/googlemaps/flutter-navigation-sdk/tree/main/doc) has 3 files in it, but each of those files are completely empty.

Looking at the version history, I can't see any previous contents in those files so perhaps they (and the directory) were added in error and should be removed.

**Comment by illuminati1911** [comment]
@bamnet  Thanks for reporting this! We'll have internal discussion about this and take action accordingly.

FYI @jokerttu

**Comment by jokerttu** [comment]
Hi @bamnet 
Those three files were not added by mistake; they are category templates. You can generate the documentation by running the command dart doc. The generated documentation is also available on [pub.dev](https://pub.dev/documentation/google_maps_navigation/latest/google_maps_navigation/google_maps_navigation-library.html)
