### ISSUE TITLE
Could not build/run on iOS

### ISSUE THREAD

**Issue by Ahmedmedhat187** [googlemaps/flutter-navigation-sdk#157]
#### Environment details
Environment version
    • Flutter version 3.22.3
    • Dart version 3.4.4
    • DevTools version 2.34.3
    
    [✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • CocoaPods version 1.15.2
    
    
#### Package version
google_maps_navigation: ^0.3.0

#### Steps to reproduce
We could not run/build on iOS

[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/projects/ios/Pods/GoogleNavigation/Frameworks/GoogleNavigation.xcframework)

We integrating dependencies as dynamic frameworks
pod file
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

**Comment by illuminati1911** [comment]
@Ahmedmedhat187 Thanks for the issue! We'll take a look at this.

**Comment by illuminati1911** [comment]
@Ahmedmedhat187 Did I understand correctly that you are trying to run the example application?

**Comment by illuminati1911** [comment]
@Ahmedmedhat187 Go to your Podfile and in target `Runner` please change the `use_frameworks!` line to `use_frameworks! :linkage => :static` to make sure your project can handle static frameworks correctly.
