### ISSUE TITLE
Classes that cannot be replaced when migrating from google_maps_flutter

### ISSUE THREAD

**Issue by yoshiya12x** [googlemaps/flutter-navigation-sdk#190]
* BitmapDescriptor
* GoogleMapsFlutterAndroid
* AndroidMapRenderer
* Cap
* JointType

When migrating from the google_maps_flutter package to the google_navigation_flutter package, I can’t find the aforementioned classes in the google_navigation_flutter package. And I can’t find what the corresponding class is.

#### Environment details
* google_maps_flutter 2.5.0
* google_navigation_flutter 0.3.0

#### Steps to reproduce
1. Migrate from the google_maps_flutter package to the google_navigation_flutter package
2. Build on iOS or Android

```
Error: Type 'BitmapDescriptor' not found.
Error: 'GoogleMapsFlutterAndroid' isn't a type.
Error: Undefined name 'AndroidMapRenderer'.
Error: The getter 'Cap' isn't defined for the class HogeHoge.
Error: The getter 'JointType' isn't defined for the class HogeHoge.
```

**Comment by jokerttu** [comment]
Hi @yoshiya12x 

The `google_navigation_flutter` package is a separate package from `google_maps_flutter` and has a different API. Please refer to the example app implementation in the repository for reference: https://github.com/googlemaps/flutter-navigation-sdk/tree/main/example

If this package lacks any features you need from `google_maps_flutter`, please open a feature request for each specific feature.
