### ISSUE TITLE
Unhandled Exception: Instance of 'SessionInitializationException'

### ISSUE THREAD

**Issue by rajesh170** [googlemaps/flutter-navigation-sdk#193]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ**

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response.

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/).

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
2. OS type and version
3. Library version and other environment information

#### Steps to reproduce

  1. ?

#### Code example

```
# example
```

#### Stack trace
``` #0      CommonNavigationSessionAPI.createNavigationSession (package:google_navigation_flutter/src/method_channel/common_session_api.dart:70:11)
E/flutter (18312): <asynchronous suspension>
E/flutter (18312): #1      GoogleMapsNavigator.initializeNavigationSession (package:google_navigation_flutter/src/navigator/google_navigation_flutter_navigator.dart:54:5)
E/flutter (18312): <asynchronous suspension>
E/flutter (18312): #2      _NavigationSampleState._initializeNavigationSession (package:clean_architecture_template/navigation_page.dart:29:5)
# example
```

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jokerttu** [comment]
Please read the `README.md` file for instructions how to setup navigation SDK.
The SessionInitializationException has code field you can read to find out the reason for the exception.
```dart
        case 'notAuthorized':
          throw const SessionInitializationException(
              SessionInitializationError.notAuthorized);
        case 'locationPermissionMissing':
          throw const SessionInitializationException(
              SessionInitializationError.locationPermissionMissing);
        case 'termsNotAccepted':
          throw const SessionInitializationException(
              SessionInitializationError.termsNotAccepted);   
```

```dart
/// Possible errors that [GoogleMapsNavigator.initializeNavigationSession] can throw.
/// {@category Navigation}
enum SessionInitializationError {
  /// The session initialization failed, because the required Maps API key is empty or invalid.
  notAuthorized,

  /// The session initialization failed, because the required location permission has not been granted.
  locationPermissionMissing,

  /// The session initialization failed, because the user has not yet accepted the navigation terms and conditions.
  termsNotAccepted
}
```
