### ISSUE TITLE
How to edit starting point

### ISSUE THREAD

**Issue by Lilian1997** [googlemaps/flutter-navigation-sdk#216]
In the example, it is currently possible to get a route from the current location to the destination using GoogleMapsNavigator.setDestinations(destinations);. I would like to know if there is a way to reset the starting point in order to obtain a route between a custom starting point and the destination, rather than from the current location. Please help! Thanks!

**Comment by jokerttu** [comment]
@Lilian1997 
You need to fetch the `routetoken` using Routes API and pass it in `CustomRouteOptions` for `setDestinations`
See example at https://github.com/googlemaps/flutter-navigation-sdk/blob/b3b5266d815561debb7ff90c70945cc0eaa8f997/example/lib/pages/navigation.dart#L812-L847

Documentation using RoutesAPI to fetch custom route here: https://developers.google.com/maps/documentation/navigation/android-sdk/customize-route for more information.

**Comment by jokerttu** [comment]
Closing as this is question, not an bug or feature requests

**Comment by jokerttu** [comment]
Closing as this is question, not an bug or feature requests

**Comment by Lilian1997** [comment]
![截圖 2024-11-15 下午2 25 37](https://github.com/user-attachments/assets/595fd9ab-2622-48bf-84e9-f4040c3a525d)

Thank you for your response. I tried modifying this part of the example to use a specified starting point instead. In the simulator, I set a current location different from the specified starting point (as shown in the image), but the result still shows a route starting from the current location. Is this the correct way to implement a custom starting point, or did I do something wrong?
```
 Future<Destinations?> _buildDestinationsWithRoutesApi() async {
    assert(_routeTokensEnabled);

    showMessage('Using route token from Routes API.');

    List<String> routeTokens = <String>[];
    
    try {
      routeTokens = await getRouteToken(
        <NavigationWaypoint>[
          // Add users location as start location for getting routetoken.
          NavigationWaypoint.withLatLngTarget(
              title: 'Origin',
              target: LatLng(latitude: 24.2181, longitude: 120.7131)),  // change here
          // title: 'Origin', target: _userLocation),
          ..._waypoints,
        ],
      );
    } catch (e) {
      showMessage('Failed to get route tokens from Routes API. $e');
      return null;
    }

    if (routeTokens.isEmpty) {
      showMessage('Failed to get route tokens from Routes API.');
      return null;
    } else if (routeTokens.length > 1) {
      showMessage(
          'More than one route token received from Routes API. Using the first one.');
    }

    return Destinations(
        waypoints: _waypoints,
        displayOptions: NavigationDisplayOptions(showDestinationMarkers: false,),
        routeTokenOptions: RouteTokenOptions(
          routeToken: routeTokens.first, // Uses first fetched route token.
          travelMode: _travelMode,
        
        ));
  }
```
![截圖 2024-11-15 下午2 26 39](https://github.com/user-attachments/assets/9c897a9c-eed2-4110-b20c-90920cc7c6f8)

**Comment by Lilian1997** [comment]
@jokerttu @Juggeli 

I’m wondering if this piece of code might be causing the issue. I tried using the `routeToken`, but it seems that `setDestination` isn’t prioritizing the `RouteTokenOptions` I passed. I’ve confirmed that the `routeToken` was successfully retrieved. However, in the example, it doesn’t appear to use the customized starting point as expected. Could you please help me check this? Thank you!

```dart
final NavigationRouteStatus navRouteStatus =
          await GoogleMapsNavigator.setDestinations(destinations);
```
