### ISSUE TITLE
Android Crash on version 0.4.0 when starting navigation

### ISSUE THREAD

**Issue by Ghelwig** [googlemaps/flutter-navigation-sdk#218]
I was having issues on Android 10 running google_navigation, so I tried upgrading to google_navigation_flutter 0.4.0. While that ended up working and the app no longer crashed on loading maps, when I start navigation I get the following error and the app crashes every time: 

D/AndroidRuntime(19972): Shutting down VM

E/AndroidRuntime(19972): FATAL EXCEPTION: main

E/AndroidRuntime(19972): Process: com.evosus.lou_service, PID: 19972

E/AndroidRuntime(19972): java.lang.NoSuchMethodError: No virtual method toSeconds()J in class Lj$/time/Duration; or its super classes (declaration of 'j$.time.Duration' appears in /data/app/com.evosus.lou_service-8vB8oPNL5DsdvGSOd7DL7w==/base.apk!classes6.dex)

E/AndroidRuntime(19972): at com.google.android.libraries.navigation.internal.sg.u.c(PG:27)

E/AndroidRuntime(19972): at com.google.android.libraries.navigation.internal.sg.t.aq(PG:3)

E/AndroidRuntime(19972): at com.google.android.libraries.geo.navcore.guidance.impl.ab.a(Unknown Source:2)

E/AndroidRuntime(19972): at com.google.android.libraries.navigation.internal.us.c.run(Unknown Source:1)

E/AndroidRuntime(19972): at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)

E/AndroidRuntime(19972): at com.google.android.libraries.navigation.internal.in.a$a.run(PG:3)

E/AndroidRuntime(19972): at android.os.Handler.handleCallback(Handler.java:873)

E/AndroidRuntime(19972): at android.os.Handler.dispatchMessage(Handler.java:99)

E/AndroidRuntime(19972): at android.os.Looper.loop(Looper.java:193)

E/AndroidRuntime(19972): at android.app.ActivityThread.main(ActivityThread.java:6831)

E/AndroidRuntime(19972): at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(19972): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)

E/AndroidRuntime(19972): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Confirmed this is happening now on Android 10 and Android 14. This is not happening on iOS. 

Steps to Reproduce: 
- Use 0.4.0 of the google_navigation_flutter package
- load the maps widget
- start navigation

We also use the "setOnRemainingTimeOrDistanceChangedListener" after we start navigation, which could potentially be whats triggering this issue.

**Comment by jokerttu** [comment]
@Ghelwig 
Than you for reporting this.
You need to enable desugaring on your application:

If minSdkVersion is set to less than 34 (API 34), you need to configure desugaring for your Android app. To enable desugaring, add the following configurations to android/app/build.gradle file:

```groovy
android {
    ...
    compileOptions {
        coreLibraryDesugaringEnabled true
        ...
    }
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs_nio:2.0.4'
}
```

You may also need to upgrade to Gradle 8.4 and the Android Gradle plugin version 8.3.0

I'll mark this as documentation issue, as this information need to be part of the README.md file.

**Comment by Ghelwig** [comment]
Hello, I upgraded our project to the Gradle Plugin 8.3.0 and Gradle 8.4 using the AGP upgrade assistant in Android Studio, and I am still getting this issue. Are there any other steps you would recommend? Thanks!

**Comment by Ghelwig** [comment]
Update, after stepping through your example project and making everything match 1:1, I was able to get it to work. It was either the wrong JavaVersion or the wrong desugar version. Thanks!
