### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by kostricanitechnology** [googlemaps/flutter-navigation-sdk#243]
**PLEASE READ**

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response.

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/).

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

I am not finding where to disable the topbar of the navigation. I tried the "initialMapToolbarEnabled: false" but is not work.

**Comment by jokerttu** [comment]
@kostricanitechnology 
See documentation for map toolbar here: https://developers.google.com/maps/documentation/android-sdk/controls#map_toolbar

To hide the navigation header, use 
`setNavigationHeaderEnabled` method of the `GoogleNavigationViewController` instance
